// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace MvcMovie.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512105446_addtable_buoi13")]
    partial class addtable_buoi13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.Device", b =>
                {
                    b.Property<string>("Device_ID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Remain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type_ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Device_ID");

                    b.HasIndex("SupplierID");

                    b.HasIndex("Type_ID");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.DeviceType", b =>
                {
                    b.Property<string>("Type_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceTypeType_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Type_ID");

                    b.HasIndex("DeviceTypeType_ID");

                    b.ToTable("DeviceType");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.IssueNote", b =>
                {
                    b.Property<string>("IN_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("IN_ID");

                    b.HasIndex("SupplierID");

                    b.ToTable("IssueNotes");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.IssueNoteDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Device_ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SumAll")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Device_ID");

                    b.HasIndex("SupplierID");

                    b.ToTable("IssueNoteDetails");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.Receipt", b =>
                {
                    b.Property<string>("ReceiptID")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReceiptID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.ReceiptDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Device_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNoteIN_ID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SumAll")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type_ID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DeviceType");

                    b.HasIndex("Device_ID");

                    b.HasIndex("IssueNoteIN_ID");

                    b.HasIndex("ReceiptID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ReceiptDetails");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.Supplier", b =>
                {
                    b.Property<string>("SupplierID")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh13.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.ChitietDH", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SumAll")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.DonHang", b =>
                {
                    b.Property<string>("OrderID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.KhachHang", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.SanPham", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Remain")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MvcMovie.Models.Entities.Faculty", b =>
                {
                    b.Property<string>("FacultyID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyID");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("MvcMovie.Models.Entities.Student", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("StudentCode");

                    b.HasIndex("FacultyID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Quan", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Quan");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.Device", b =>
                {
                    b.HasOne("MvcMovie.Models.Baithuchanh12.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID");

                    b.HasOne("MvcMovie.Models.Baithuchanh12.DeviceType", "DeviceTypes")
                        .WithMany("Devices")
                        .HasForeignKey("Type_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceTypes");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.DeviceType", b =>
                {
                    b.HasOne("MvcMovie.Models.Baithuchanh12.DeviceType", null)
                        .WithMany("DeviceTypes")
                        .HasForeignKey("DeviceTypeType_ID");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.IssueNote", b =>
                {
                    b.HasOne("MvcMovie.Models.Baithuchanh12.Supplier", "Supplier")
                        .WithMany("IssuNotes")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.IssueNoteDetails", b =>
                {
                    b.HasOne("MvcMovie.Models.Baithuchanh12.Device", "Device")
                        .WithMany("IssueNoteDetails")
                        .HasForeignKey("Device_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MvcMovie.Models.Baithuchanh12.Supplier", "Supplier")
                        .WithMany("IssuNoteDetails")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.Receipt", b =>
                {
                    b.HasOne("MvcMovie.Models.Baithuchanh12.Supplier", "Supplier")
                        .WithMany("Receipts")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.ReceiptDetails", b =>
                {
                    b.HasOne("MvcMovie.Models.Baithuchanh12.DeviceType", "DeviceTypes")
                        .WithMany()
                        .HasForeignKey("DeviceType");

                    b.HasOne("MvcMovie.Models.Baithuchanh12.Device", "Device")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("Device_ID");

                    b.HasOne("MvcMovie.Models.Baithuchanh12.IssueNote", null)
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("IssueNoteIN_ID");

                    b.HasOne("MvcMovie.Models.Baithuchanh12.Receipt", "Receipts")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("ReceiptID");

                    b.HasOne("MvcMovie.Models.Baithuchanh12.Supplier", "Supplier")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("SupplierID");

                    b.Navigation("Device");

                    b.Navigation("DeviceTypes");

                    b.Navigation("Receipts");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.ChitietDH", b =>
                {
                    b.HasOne("MvcMovie.Models.Baithuchanh9.DonHang", "Orders")
                        .WithMany("Details")
                        .HasForeignKey("OrderID");

                    b.HasOne("MvcMovie.Models.Baithuchanh9.SanPham", "Products")
                        .WithMany("Details")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.DonHang", b =>
                {
                    b.HasOne("MvcMovie.Models.Baithuchanh9.KhachHang", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MvcMovie.Models.Entities.Student", b =>
                {
                    b.HasOne("MvcMovie.Models.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyID");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.Device", b =>
                {
                    b.Navigation("IssueNoteDetails");

                    b.Navigation("ReceiptDetails");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.DeviceType", b =>
                {
                    b.Navigation("DeviceTypes");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.IssueNote", b =>
                {
                    b.Navigation("ReceiptDetails");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.Receipt", b =>
                {
                    b.Navigation("ReceiptDetails");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh12.Supplier", b =>
                {
                    b.Navigation("IssuNoteDetails");

                    b.Navigation("IssuNotes");

                    b.Navigation("ReceiptDetails");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.DonHang", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.KhachHang", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MvcMovie.Models.Baithuchanh9.SanPham", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("MvcMovie.Models.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
